config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users do
    resources :games
  end

  resources :games do
    collection do
      post 'addplayer'
      post 'create'
    end

    member do
      resources :gamemanagers do
        post 'play_card'
        post 'play_card_action'
        post 'end_card_action'
        post 'next_phase'
        post 'buy_card'
      end
    end
  end

end

app/models/game.rb
class Game < ActiveRecord::Base
  validate :has_at_least_two_players
  has_one :gamemanager, dependent: :destroy
  has_many :players, dependent: :destroy
  has_one :supply, class_name: "Deck", foreign_key: "game_id", dependent: :destroy
  has_one :trash, class_name: "Deck", foreign_key: "game_id", dependent: :destroy

    # Returns a string containing a list of all the users currently playing in this game
    def get_player_list
      players.map { |p| "Player " + p.turn_order.to_s + ": " + p.name + " | " }.join.to(-3)
    end

    # Updates the status of the game to "Finished" and cleans up any unnecessary data
    def end_game
      update_attributes(status: "Finished" )
    end

    # Creates a player for the provided user_id and adds them to this game
    def add_user_to_game(user_id)
      players.create!(user_id: user_id, turn_order: ( (players.maximum('turn_order') || 0) + 1) )
    end

    # Returns a new game with new created players from the array of users passed to this method
    def Game.create_game_for(creator_id, user_array)
      game = Game.create(status: "In Progress")
      # Randomize turn order - ensure the creator is the first player and randomize other players order
      opponents_array = user_array
      players_array = opponents_array.shuffle.insert(0, User.find(creator_id))
      turn_order_counter = 1
      # Create players for each user
      players_array.each do |u|
        game.players.create(user_id: u.id, turn_order: turn_order_counter)
        turn_order_counter += 1
      end 
      # Create gamemanager
      game.create_gamemanager(phase: "Action", actions: 1, treasure: 0, buys: 1, player_turn: game.players.find_by(turn_order: 1).id)
      # Initialize Supply counts
      game.gamemanager.initialize_supply_count("Copper", 15)
      game.gamemanager.initialize_supply_count("Silver", 15)
      game.gamemanager.initialize_supply_count("Gold", 15)
      game.gamemanager.initialize_supply_count("Estate", 15)
      game.gamemanager.initialize_supply_count("Duchy", 15)
      game.gamemanager.initialize_supply_count("Province", 15)
      game.gamemanager.initialize_supply_count("Village", 15)
      game.gamemanager.initialize_supply_count("Laboratory", 15)
      game.gamemanager.initialize_supply_count("Council Room", 15)
      game.gamemanager.initialize_supply_count("Festival", 15)
      game.gamemanager.initialize_supply_count("Cellar", 15)
      game.gamemanager.initialize_supply_count("Mine", 15)
      game.gamemanager.initialize_supply_count("Bureaucrat", 15)
      game.gamemanager.initialize_supply_count("Smithy", 15)
      game.gamemanager.initialize_supply_count("Woodcutter", 15)
      game.gamemanager.initialize_supply_count("Witch", 15)
      # Returns game
      return game
    end

    # Creates decks for supply and players and intial cards for all the players
    def initialize_player_cards
      create_supply_decks
      players.each do |p|
        create_player_decks(p)
        create_player_cards(p)
        p.draw_card(5)
      end
    end

    # Creates a hash of the supply card object as the key value and the count in the supply as the value
    def generate_supply_cards_hash
      unless self.gamemanager.supply_count.nil?
        @supply_cards_hash = {}
        self.gamemanager.supply_count.each do |key, value|
          mapping = Cardmapping.find_by(name: key)
          @supply_cards_hash.store( mapping.name, { "cost" => mapping.cost, "text" => mapping.text, "count" => value } )
          if mapping.is_treasure
            @supply_cards_hash[mapping.name].store( "treasure_amount", mapping.treasure_amount )
          end
          if mapping.is_victory
            @supply_cards_hash[mapping.name].store( "victory_points", mapping.victory_points )
          end
        end
      end
      return @supply_cards_hash
    end

    # Return an array listing the name of supply cards that match the provided parameters 
    def generate_selectable_supply_array(type = nil, min_cost = nil, max_cost = nil, names_array = nil)
      query = ""

      # check by type
      query = query + " and is_" + type.downcase + " = 't'" unless type.nil?
      # check by min cost
      query = query + " and cost >= " + min_cost.to_s unless min_cost.nil?
      # check by max cost
      query = query + " and cost <= " + max_cost.to_s unless max_cost.nil?
      # check by name
      unless names_array.nil?
        query = query + " and name in ("
        count = 0
        names_array.each do |n|
          count = count + 1
          query = query + "'" + n + "'"
          query = query + "," unless count == names_array.length
        end
        query = query + ")"
      end

      unless query.blank?
        query.prepend("select name from cardmappings where 1=1")
        # check only for cards that exist in the current games supply
        query = query + " and name in ('" + self.gamemanager.supply_count.keys.join("','") + "')"
        mappings_objs = Cardmapping.find_by_sql(query)
        # create an array of names from the objects found
        supply_array = []
        mappings_objs.each do |m|
          supply_array.push(m.name)
        end
        return supply_array
      end
    end


    private

      # Validates that the game has 2 players before it is saved
      def has_at_least_two_players
        errors.add(:players, "should have at least 2 players") if  (players.nil? or players.size == 1)
      end

      # Create Supply, Hand, Discard decks for a given player
      def create_player_decks(player)
        if player
          player.create_supply(game_id: self.id, player_id: player.id , status: 'Supply')
          player.create_hand(game_id: self.id, player_id: player.id , status: 'Hand')
          player.create_discard(game_id: self.id, player_id: player.id , status: 'Discard')
          player.create_played(game_id: self.id, player_id: player.id , status: 'Played')
        end
      end

      # Create the initial cards in each players supply
      def create_player_cards(player)
        if player.supply
          7.times { player.supply.cards.create!( cardmapping_id: Cardmapping.get( 'Copper' ) ) }
          3.times { player.supply.cards.create!( cardmapping_id: Cardmapping.get( 'Estate' ) ) }
          # Testing purposes
          #3.times { player.supply.cards.create!( cardmapping_id: Cardmapping.get( 'Mine' ) ) }
          player.supply.shuffle
        end
      end

      # Create Trash deck for the game
      def create_supply_decks
        Deck.create(game_id: id, player_id: -1, status: 'Trash')
      end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  include GamesHelper

  def index
    @games = User.find(params[:user_id]).games
  end

  def show
    @game = Game.find(params[:id])
    @player = current_player(@game.id)
    @supply_cards = @game.generate_supply_cards_hash
  end

  def new
    @game_players = nil
    @game_users = []
    @avail_users = User.where('id != ?', current_user.id)
    @creator_id = current_user.id
  end

  def addplayer
    (params[:game_players].nil? or params[:game_players].blank?) ? @game_players = params[:player].to_s : @game_players = params[:game_players].to_s + ',' + params[:player].to_s
    convert_game_players_array(@game_players)
    @avail_users = User.where.not(id: (@game_players + ',' + current_user.id.to_s).to_s.split(','))
    @creator_id = current_user.id
    render '/games/new'
  end

  def create
    @game_players = params[:game_players].to_s
    convert_game_players_array(@game_players)
    @game = Game.create_game_for(current_user.id, @game_users)
    if @game.valid?
      @game.initialize_player_cards
      flash[:success] = "New Game Started!"
      redirect_to @game
    else
      render '/games/new'
    end
  end

  def destroy
    if current_user.id  == Game.find(params[:id]).players.find_by(turn_order: 1).user_id
      Game.find(params[:id]).destroy
      flash[:success] = "Game deleted"
    end
    redirect_to user_games_path(current_user.id)
  end

end

app/helpers/games_helper.rb
module GamesHelper

  def convert_game_players_array(game_players)
    #puts 'game_players = ' + game_players.to_s
    (game_players.nil? or game_players.blank?) ? @game_users = [] : 
      (game_players.include?(',') ? @game_users = User.find( game_players.to_s.split(',') ) : @game_users = [ User.find(game_players) ] )
    #puts '@game_users = !' + @game_users.to_s + '!'
  end

end

app/views/games/_game.html.erb
<li>
  Start Date: <%= game.created_at %></br>
  <%= game.get_player_list %></br>
  <%= link_to "Continue Game", user_game_path(id: game.id) %>
  <% if game.players.find_by(turn_order: 1).id == Player.find_by(user_id: current_user.id, game_id: game.id).id %>
    | <%= link_to "delete", game, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/games/_game_board.html.erb
  <div class="col-md-12">

    <%= render('games/game_board_turn_info') %>

    <%= render('games/game_board_played_supply_cards') %>

    <%= render('games/game_board_player_panel') %>

  </div>

app/views/games/_game_board_played_supply_cards.html.erb
  <div class="played_supply_cards">
    <div class="col-md-6 panel panel-info">
      <div class="panel-heading">
        <b>played_cards</b>
      </div>
      <div class="panel-body">
        <div class="played_cards">
          <% unless @player.played.nil? || @player.played.empty? %>
            <%= render @player.played.cards %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-6 panel panel-info">
      <div class="panel-heading">
        <b>supply_cards</b>
      </div>
      <div class="panel-body">
      <div class="supply_cards">
        <% if @supply_cards %>
          <% @supply_cards.each do |key, val| %>
            <%= render :partial => 'cards/supply_card', :locals => { :name => key, :values => val} %>
          <% end %>
        <% end %>
      </div>
      </div>
    </div>
  </div>

app/views/games/_game_board_player_panel.html.erb
  <div class="col-md-12 player_panel">

      <%= render :partial => 'cards/player_deck', :locals => { :name => 'Supply', :card_count => @player.supply.cards.size } %>

      <div class="col-md-8 panel panel-info">
        <div class="panel-heading">
          <b>player_hand</b>
        </div>
        <div class="panel-body">
          <div class="hand_cards">
            <% unless @player.hand.nil? || @player.hand.empty? %>
              <%= render @player.hand.cards %>
            <% end %>
          </div>
        </div>
      </div>

      <%= render :partial => 'cards/player_deck', :locals => { :name => 'Discard', :card_count => @player.discard.cards.size } %>

  </div>

app/views/games/_game_board_turn_info.html.erb
    <div class="turn_info">
      <div class"col-md-12">

        <div class="card_info">
          <b>instructions</b>
          <p class="text-info">
          <% if current_player_turn?(@game.id) %>

            <% if @game.gamemanager.prompt %>
              <%=raw @game.gamemanager.prompt %>
            <% end %>

            <% if @game.gamemanager.action_phase.nil? %>
              <%= form_tag("/games/" + @game.id.to_s + "/gamemanagers/" + @game.gamemanager.id.to_s + "/next_phase", remote: true) do %>
                <br /><div class="instruction_button"><%= submit_tag "End " + @game.gamemanager.phase + " Phase", class: "btn btn-primary btn-xs" %></div>
              <% end %>
            <% else %>
              <%= form_tag("/games/" + @game.id.to_s + "/gamemanagers/" + @game.gamemanager.id.to_s + "/end_card_action", remote: true) do %>
                <br /><div class="instruction_button"><%= submit_tag "End " + @game.gamemanager.action_phase + " Phase", class: "btn btn-warning btn-xs" %></div>
              <% end %>
            <% end %>

          <% else %>
            It's not your turn!
          <% end %>
          </p>
        </div>

        <div class="game_info">
          <p class="text-primary">
          <b>Player Turn:</b> <%= @game.gamemanager.current_player_name %><br />
          <b>Phase:</b> <%= @game.gamemanager.phase %><br />
          <% if current_player_turn?(@game.id) %>
            <b>Treasure:</b> <%= @game.gamemanager.current_treasure_balance %> | <b>Actions:</b> <%= @game.gamemanager.actions %> | <b>Buys:</b> <%= @game.gamemanager.buys %>
          <% end %>
          </p>
        </div>

      </div>
    </div>

app/views/games/index.html.erb
<% provide(:title, 'All Games') %>
<h1>All Games</h1>

<%= link_to "New Game", new_user_game_path %></ br>

<% if @games.empty? %>
You are not in any games right now!
<% else %>
  <ul class="users">
    <% @games.each do |game| %>
      <%= render game %>
    <% end %>
  </ul>
<% end %>

app/views/games/new.html.erb
<% provide(:title, 'New Game') %>
<h1>Create A New Game</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_tag "/games/addplayer" do %>
      <% if @game_users.size < 5 %>
        <span class = "glyphicon glyphicon-user"></span>  <%= label_tag 'player', 'Add Player (Max 5 Players)' %>
        <%= select_tag 'player', options_from_collection_for_select( @avail_users, 'id', 'name')  %>
      <% end %>

      <% if @game_users.any? %>
        <% @game_users.each do |user| %>
          <ol>
            <%= gravatar_for user, size: 20 %>
            <%= link_to user.name, user %>
          </ol>
        <% end %>
      <% end %>

      <% if @game_users.size < 5 %>
        <%= hidden_field_tag 'game_players', @game_players.to_s %>
        <%= hidden_field_tag 'creator_id', @creator_id.to_s %>
        <%= submit_tag "Add Player", class: "btn btn-primary" %>
      <% end %>
    <% end %>
      
    <% if @game_users.size > 1 %>
      <%= form_tag "/games/create" do %>
        <%= hidden_field_tag 'game_players', @game_players.to_s %>
        <%= hidden_field_tag 'creator_id', @creator_id.to_s %>
        <%= submit_tag "Create Game", class: "btn btn-primary" %>
      <% end %>
    <% end %>

  </div>
</div>

app/views/games/show.html.erb
<% provide(:title, "Game") %>

<div class="game_board" id="game_board">
  <%= render('games/game_board') %>
</div>